# permissions for end users to view listeners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: listener-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: xds
    app.kubernetes.io/part-of: xds
    app.kubernetes.io/managed-by: kustomize
  name: listener-viewer-role
rules:
- apiGroups:
  - lds.envoyxds.io
  resources:
  - listeners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lds.envoyxds.io
  resources:
  - listeners/status
  verbs:
  - get
