---
# TLSSecret using Let's Encrypt with DNS01 challenge
# Note: Requires CLOUDFLARE_DNS_API_TOKEN environment variable
apiVersion: envoyxds.io/v1alpha1
kind: TLSSecret
metadata:
  name: example-domain
spec:
  domains:
    - "example.org"
  challenge:
    challenge_type: DNS01
    dns01_provider: cloudflare
    acme_env: Staging
---
# TLSSecret with local certificate storage
# Certificates will be stored in ./certs directory
apiVersion: envoyxds.io/v1alpha1
kind: TLSSecret
metadata:
  name: example-local
spec:
  domains:
    - "*.example.local"
  config:
    type: Local
    local_config:
      path: ./certs
