---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xds-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xds-controller
subjects:
  - kind: ServiceAccount
    name: xds-controller
    namespace: xds-system
